name: deploy

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Build and Deploy
              uses: ./.github/actions/deploy
              env:
                  COMMIT_EMAIL: jeoy_z@126.com
                  COMMIT_NAME: jeoy
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BASE_BRANCH: master # The branch the action should deploy from.
                  DEPLOY_BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: dist # The folder the action should deploy.
                  BUILD_SCRIPT: yarn && npm run-script build # The build script the action should run prior to deploying.
